=== zzambers/thermostat-ng_agent/distribution/docs/thermostat-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://icedtea.classpath.org/thermostat/plugins/v1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://icedtea.classpath.org/thermostat/plugins/v1.0"
           elementFormDefault="qualified">


<!-- definition of simple elements -->
<xs:element name="name" type="xs:string"/>

<xs:element name="symbolic-name" type="xs:string"/>

<xs:element name="version" type="xs:string"/>

<xs:element name="usage" type="xs:string"/>

<xs:element name="summary" type="xs:string">
  <xs:annotation>
    <xs:documentation>A very short summary of what this command does.
    Ideally around 50 characters.</xs:documentation>
  </xs:annotation>
</xs:element>

<xs:element name="description" type="xs:string">
  <xs:annotation>
    <xs:documentation>A complete description of what this command
    does. Can be long.</xs:documentation>
  </xs:annotation>
</xs:element>

<xs:element name="short" type="xs:string"/>

<xs:element name="long" type="xs:string"/>

<xs:element name="argument" type="xs:string"/>

<xs:element name="required" type="xs:boolean"/>

<xs:element name="id" type="xs:string"/>

<xs:element name="configuration" type="xs:string"/>


<!-- definition of complex elements -->
<xs:element name="plugin">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="id" minOccurs="0" maxOccurs="1"/>
      <xs:choice>
        <xs:sequence>
          <xs:element ref="commands"/>
          <xs:element ref="extensions" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:element ref="extensions"/>
      </xs:choice>
      <xs:element ref="configurations" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="commands">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="command" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="extensions">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="extension" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="extension">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="bundles"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="command">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="usage" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="summary" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="description"/>
      <xs:element ref="arguments" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="options" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="environments"/>
      <xs:element ref="bundles"/>
    </xs:sequence>
  </xs:complexType>
</xs:element> 


<xs:element name="arguments">
  <xs:complexType>
    <xs:annotation>
      <xs:documentation>
        "Arguments" tag has been set as optional for commands that don't need any specified argument 
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element ref="argument" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="options">
  <xs:complexType>
    <xs:annotation>
      <xs:documentation>
        "Options" tag has been set as optional for commands that don't need any specified option 
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element ref="group" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="option" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="group">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="required" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="option" minOccurs="2" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="option">
  <xs:complexType>
    <xs:sequence>
      <xs:choice>
        <xs:sequence>
          <xs:element ref="long"/>
          <xs:element ref="short" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:element ref="short"/>
      </xs:choice>
      <xs:element ref="argument" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="required" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="common" type="xs:boolean" use="optional"/>
  </xs:complexType>
</xs:element>

<xs:element name="environments">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="environment" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="environment">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="shell">
        <xs:annotation>
          <xs:documentation>Indicates that the command is available to be invoked from within the thermostat shell.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="cli">
        <xs:annotation>
          <xs:documentation>Indicates that the command is available to be invoked as an argument to the main thermostat program.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="bundles">
  <xs:annotation>
    <xs:documentation>
      Specifies OSGi bundles
    </xs:documentation>
  </xs:annotation>
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="bundle" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="bundle">
  <xs:annotation>
    <xs:documentation>
      Specifies an OSGi bundle
    </xs:documentation>
  </xs:annotation>
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="symbolic-name">
        <xs:annotation>
          <xs:documentation>
            The 'Bundle-SymbolicName' of the OSGi bundle
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element ref="version">
        <xs:annotation>
          <xs:documentation>
            The 'Bundle-Version' of the OSGi bundle
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="configurations">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="configuration" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== zzambers/thermostat-ng_agent/dependency-tool/distribution/thermostat-plugin.xml
<!--

 Copyright 2012-2016 Red Hat, Inc.

 This file is part of Thermostat.

 Thermostat is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation; either version 2, or (at your
 option) any later version.

 Thermostat is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Thermostat; see the file COPYING.  If not see
 <http://www.gnu.org/licenses/>.

 Linking this code with other modules is making a combined work
 based on this code.  Thus, the terms and conditions of the GNU
 General Public License cover the whole combination.

 As a special exception, the copyright holders of this code give
 you permission to link this code with independent modules to
 produce an executable, regardless of the license terms of these
 independent modules, and to copy and distribute the resulting
 executable under terms of your choice, provided that you also
 meet, for each linked independent module, the terms and conditions
 of the license of that module.  An independent module is a module
 which is not derived from or based on this code.  If you modify
 this code, you may extend this exception to your version of the
 library, but you are not obligated to do so.  If you do not wish
 to do so, delete this exception statement from your version.

-->
<plugin xmlns="http://icedtea.classpath.org/thermostat/plugins/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icedtea.classpath.org/thermostat/plugins/v1.0 http://icedtea.classpath.org/thermostat/docs/1.0/thermostat-plugin.xsd">
    <commands>
        <command>
            <name>dependency-analyzer</name>
            <summary>Analyse OSGi dependencies for the selected libray</summary>
            <description>Analyse OSGi dependencies for the selected library</description>
            <options>

                <option>
                    <long>list-all</long>
                    <required>false</required>
                    <description>List all the jars available on the Thermostat classpath</description>
                </option>

                <option>
                    <long>exports</long>
                    <argument>jar&gt; || &lt;package</argument>
                    <required>false</required>
                    <description>Lists only the packages that this jar file or package exports</description>
                </option>

                <option>
                    <long>imports</long>
                    <argument>jar&gt; || &lt;package</argument>
                    <required>false</required>
                    <description>Lists only the packages that this jar file or package imports</description>
                </option>

                <option>
                    <long>outbound</long>
                    <argument>jar&gt; || &lt;package</argument>
                    <required>false</required>
                    <description>Similar to "imports", but with a list of jar files rather than single packages, upon which this jar or package depends</description>
                </option>

                <option>
                    <long>inbound</long>
                    <argument>jar&gt; || &lt;package</argument>
                    <required>false</required>
                    <description>List every library that has a dependency on this one</description>
                </option>

                <option>
                    <long>whatprovides</long>
                    <argument>package</argument>
                    <required>false</required>
                    <description>Prints the jar file that exports the given package</description>
                </option>

            </options>
            <environments>
                <environment>cli</environment>
            </environments>
            <bundles>
                <bundle>
                    <symbolic-name>com.redhat.thermostat.tools.dependency</symbolic-name>
                    <version>${project.version}</version>
                </bundle>
            </bundles>
        </command>
    </commands>
</plugin>

=== zzambers/thermostat-ng_agent/storage-profile/distribution/thermostat-plugin.xml
<?xml version="1.0"?>
<!--

 Copyright 2012-2014 Red Hat, Inc.

 This file is part of Thermostat.

 Thermostat is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation; either version 2, or (at your
 option) any later version.

 Thermostat is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Thermostat; see the file COPYING.  If not see
 <http://www.gnu.org/licenses/>.

 Linking this code with other modules is making a combined work
 based on this code.  Thus, the terms and conditions of the GNU
 General Public License cover the whole combination.

 As a special exception, the copyright holders of this code give
 you permission to link this code with independent modules to
 produce an executable, regardless of the license terms of these
 independent modules, and to copy and distribute the resulting
 executable under terms of your choice, provided that you also
 meet, for each linked independent module, the terms and conditions
 of the license of that module.  An independent module is a module
 which is not derived from or based on this code.  If you modify
 this code, you may extend this exception to your version of the
 library, but you are not obligated to do so.  If you do not wish
 to do so, delete this exception statement from your version.

-->
<plugin xmlns="http://icedtea.classpath.org/thermostat/plugins/v1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://icedtea.classpath.org/thermostat/plugins/v1.0 thermostat-plugin.xsd">
  <commands>
    <command>
      <name>storage-profile</name>
      <description>profile how fast storage operations are</description>
      <options>
        <option common="true">
          <long>dbUrl</long>
        </option>
        <option>
          <long>iterations</long>
          <short>i</short>
          <argument>number</argument>
          <required>false</required>
          <description>the number of iterations to run for each benchmark</description>
        </option>
      </options>
      <environments>
        <environment>cli</environment>
        <environment>shell</environment>
      </environments>
      <bundles>
        <bundle><symbolic-name>com.redhat.thermostat.client.cli</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.storage.profile</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.storage.mongodb</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.web.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.web.client</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>${osgi.compendium.bundle.symbolic-name}</symbolic-name><version>${osgi.compendium.osgi-version}</version></bundle>
        <bundle><symbolic-name>org.apache.httpcomponents.httpcore</symbolic-name><version>${httpcomponents.core.version}</version></bundle>
        <bundle><symbolic-name>org.apache.httpcomponents.httpclient</symbolic-name><version>${httpcomponents.client.version}</version></bundle>
        <bundle><symbolic-name>com.google.gson</symbolic-name><version>${gson.version}</version></bundle>
        <bundle><symbolic-name>org.mongodb.mongo-java-driver</symbolic-name><version>${mongo-driver.osgi-version}</version></bundle>
        <bundle><symbolic-name>org.apache.commons.beanutils</symbolic-name><version>${commons-beanutils.version}</version></bundle>
        <bundle><symbolic-name>org.apache.commons.codec</symbolic-name><version>${commons-codec.osgi-version}</version></bundle>
        <bundle><symbolic-name>org.apache.commons.collections</symbolic-name><version>${commons-collections.version}</version></bundle>
        <bundle><symbolic-name>org.apache.commons.logging</symbolic-name><version>${commons-logging.version}</version></bundle>
      </bundles>
    </command>
  </commands>
</plugin>

=== zzambers/thermostat-ng_agent/vm-jmx/distribution/thermostat-plugin.xml
<?xml version="1.0"?>
<!--

 Copyright 2012-2017 Red Hat, Inc.

 This file is part of Thermostat.

 Thermostat is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation; either version 2, or (at your
 option) any later version.

 Thermostat is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Thermostat; see the file COPYING.  If not see
 <http://www.gnu.org/licenses/>.

 Linking this code with other modules is making a combined work
 based on this code.  Thus, the terms and conditions of the GNU
 General Public License cover the whole combination.

 As a special exception, the copyright holders of this code give
 you permission to link this code with independent modules to
 produce an executable, regardless of the license terms of these
 independent modules, and to copy and distribute the resulting
 executable under terms of your choice, provided that you also
 meet, for each linked independent module, the terms and conditions
 of the license of that module.  An independent module is a module
 which is not derived from or based on this code.  If you modify
 this code, you may extend this exception to your version of the
 library, but you are not obligated to do so.  If you do not wish
 to do so, delete this exception statement from your version.

-->
<plugin xmlns="http://icedtea.classpath.org/thermostat/plugins/v1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://icedtea.classpath.org/thermostat/plugins/v1.0 thermostat-plugin.xsd">
  <commands>
    <command>
      <name>notifications</name>
      <summary>manage JMX notifications on the given VM</summary>
      <description>Manage JMX notification monitoring on the given JVM.</description>
      <subcommands>
        <subcommand>
          <name>status</name>
          <description>Check JMX notification monitoring status</description>
        </subcommand>
        <subcommand>
          <name>enable</name>
          <description>Enable JMX notification monitoring</description>
          <options>
            <option>
              <long>follow</long>
              <short>f</short>
              <required>false</required>
              <description>Start following JMX events immediately</description>
            </option>
          </options>
        </subcommand>
        <subcommand>
          <name>disable</name>
          <description>Disable JMX notification monitoring</description>
        </subcommand>
        <subcommand>
          <name>follow</name>
          <description>Follow JMX notification events</description>
        </subcommand>
        <subcommand>
          <name>show</name>
          <description>Show all JMX events for the JVM</description>
          <options>
            <option>
              <long>since</long>
              <argument>time</argument>
              <description>only show events occurring since the given instant. Dates must be expressed 1) in milliseconds
                since the Unix epoch, or 2) as an integer offset from present in seconds, minutes, hours, or days, of
                the form "30s" for the last 30 seconds, or "1d" for the last day, for example.</description>
            </option>
          </options>
        </subcommand>
      </subcommands>
      <options>
        <option>
          <long>vmId</long>
          <short>v</short>
          <argument>id</argument>
          <required>true</required>
        </option>
      </options>
      <environments>
        <environment>cli</environment>
        <environment>shell</environment>
      </environments>
      <bundles>
        <bundle><symbolic-name>com.redhat.thermostat.vm.jmx.client.cli</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.vm.jmx.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.vm.jmx.client.core</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.web.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.web.client</symbolic-name><version>${project.version}</version></bundle>
      </bundles>
    </command>
  </commands>

  <extensions>
    <extension>
      <name>gui</name>
      <bundles>
        <bundle><symbolic-name>com.redhat.thermostat.vm.jmx.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.vm.jmx.client.core</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.vm.jmx.client.swing</symbolic-name><version>${project.version}</version></bundle>
      </bundles>
    </extension>
    <extension>
      <name>agent</name>
      <bundles>
        <bundle><symbolic-name>com.redhat.thermostat.vm.jmx.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.vm.jmx.agent</symbolic-name><version>${project.version}</version></bundle>
      </bundles>
    </extension>
  </extensions>
</plugin>

=== zzambers/thermostat-ng_agent/vm-gc/distribution/thermostat-plugin.xml
<?xml version="1.0"?>
<!--

 Copyright 2012-2015 Red Hat, Inc.

 This file is part of Thermostat.

 Thermostat is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation; either version 2, or (at your
 option) any later version.

 Thermostat is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Thermostat; see the file COPYING.  If not see
 <http://www.gnu.org/licenses/>.

 Linking this code with other modules is making a combined work
 based on this code.  Thus, the terms and conditions of the GNU
 General Public License cover the whole combination.

 As a special exception, the copyright holders of this code give
 you permission to link this code with independent modules to
 produce an executable, regardless of the license terms of these
 independent modules, and to copy and distribute the resulting
 executable under terms of your choice, provided that you also
 meet, for each linked independent module, the terms and conditions
 of the license of that module.  An independent module is a module
 which is not derived from or based on this code.  If you modify
 this code, you may extend this exception to your version of the
 library, but you are not obligated to do so.  If you do not wish
 to do so, delete this exception statement from your version.

-->
<plugin xmlns="http://icedtea.classpath.org/thermostat/plugins/v1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://icedtea.classpath.org/thermostat/plugins/v1.0 thermostat-plugin.xsd">
  <commands>
    <command>
      <name>gc</name>
      <summary>perform Garbage Collection on the given vm</summary>
      <description>Perform Garbage Collection on the given vm.</description>
      <options>
        <option>
          <long>vmId</long>
          <short>v</short>
          <argument>vm</argument>
          <required>true</required>
          <description>the ID of the VM</description>
        </option>
      </options>
      <environments>
        <environment>cli</environment>
        <environment>shell</environment>
      </environments>
      <bundles>
        <bundle><symbolic-name>com.redhat.thermostat.vm.gc.command</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.gc.remote.client.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.gc.remote.common.command</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.common.command</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.client.core</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.client.command</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.client.cli</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.storage.mongodb</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.web.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.web.client</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>org.mongodb.mongo-java-driver</symbolic-name><version>${mongo-driver.osgi-version}</version></bundle>
        <bundle><symbolic-name>org.apache.commons.beanutils</symbolic-name><version>${commons-beanutils.version}</version></bundle>
        <bundle><symbolic-name>org.apache.commons.codec</symbolic-name><version>${commons-codec.osgi-version}</version></bundle>
        <bundle><symbolic-name>org.apache.commons.collections</symbolic-name><version>${commons-collections.version}</version></bundle>
        <bundle><symbolic-name>org.apache.commons.logging</symbolic-name><version>${commons-logging.version}</version></bundle>
        <bundle><symbolic-name>org.apache.httpcomponents.httpcore</symbolic-name><version>${httpcomponents.core.version}</version></bundle>
        <bundle><symbolic-name>org.apache.httpcomponents.httpclient</symbolic-name><version>${httpcomponents.client.version}</version></bundle>
        <bundle><symbolic-name>${osgi.compendium.bundle.symbolic-name}</symbolic-name><version>${osgi.compendium.osgi-version}</version></bundle>
        <bundle><symbolic-name>com.google.gson</symbolic-name><version>${gson.version}</version></bundle>
        <bundle><symbolic-name>org.jboss.netty</symbolic-name><version>${netty.version}</version></bundle>
      </bundles>
    </command>
  </commands>
  <extensions>
    <extension>
      <name>gui</name>
      <bundles>
        <bundle><symbolic-name>com.redhat.thermostat.vm.gc.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.vm.gc.client.core</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.vm.gc.client.swing</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.gc.remote.common.command</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.gc.remote.client.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.gc.remote.client.swing</symbolic-name><version>${project.version}</version></bundle>
      </bundles>
    </extension>
    <extension>
      <name>agent</name>
      <bundles>
        <bundle><symbolic-name>com.redhat.thermostat.vm.gc.common</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.vm.gc.agent</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.gc.remote.common.command</symbolic-name><version>${project.version}</version></bundle>
        <bundle><symbolic-name>com.redhat.thermostat.gc.remote.command</symbolic-name><version>${project.version}</version></bundle>
      </bundles>
    </extension>
  </extensions>
  <!-- TODO: Need to express dependency on vm-memory-common -->
</plugin>
