=== zzambers/thermostat-ng_agent/distribution/docs/thermostat-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://icedtea.classpath.org/thermostat/plugins/v1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://icedtea.classpath.org/thermostat/plugins/v1.0"
           elementFormDefault="qualified">


<!-- definition of simple elements -->
<xs:element name="name" type="xs:string"/>

<xs:element name="symbolic-name" type="xs:string"/>

<xs:element name="version" type="xs:string"/>

<xs:element name="usage" type="xs:string"/>

<xs:element name="summary" type="xs:string">
  <xs:annotation>
    <xs:documentation>A very short summary of what this command does.
    Ideally around 50 characters.</xs:documentation>
  </xs:annotation>
</xs:element>

<xs:element name="description" type="xs:string">
  <xs:annotation>
    <xs:documentation>A complete description of what this command
    does. Can be long.</xs:documentation>
  </xs:annotation>
</xs:element>

<xs:element name="short" type="xs:string"/>

<xs:element name="long" type="xs:string"/>

<xs:element name="argument" type="xs:string"/>

<xs:element name="required" type="xs:boolean"/>

<xs:element name="id" type="xs:string"/>

<xs:element name="configuration" type="xs:string"/>


<!-- definition of complex elements -->
<xs:element name="plugin">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="id" minOccurs="0" maxOccurs="1"/>
      <xs:choice>
        <xs:sequence>
          <xs:element ref="commands"/>
          <xs:element ref="extensions" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:element ref="extensions"/>
      </xs:choice>
      <xs:element ref="configurations" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="commands">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="command" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="extensions">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="extension" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="extension">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="bundles"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="command">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="name"/>
      <xs:element ref="usage" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="summary" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="description"/>
      <xs:element ref="arguments" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="options" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="environments"/>
      <xs:element ref="bundles"/>
    </xs:sequence>
  </xs:complexType>
</xs:element> 


<xs:element name="arguments">
  <xs:complexType>
    <xs:annotation>
      <xs:documentation>
        "Arguments" tag has been set as optional for commands that don't need any specified argument 
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element ref="argument" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="options">
  <xs:complexType>
    <xs:annotation>
      <xs:documentation>
        "Options" tag has been set as optional for commands that don't need any specified option 
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element ref="group" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="option" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="group">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="required" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="option" minOccurs="2" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="option">
  <xs:complexType>
    <xs:sequence>
      <xs:choice>
        <xs:sequence>
          <xs:element ref="long"/>
          <xs:element ref="short" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:element ref="short"/>
      </xs:choice>
      <xs:element ref="argument" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="required" minOccurs="0" maxOccurs="1"/>
      <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="common" type="xs:boolean" use="optional"/>
  </xs:complexType>
</xs:element>

<xs:element name="environments">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="environment" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="environment">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="shell">
        <xs:annotation>
          <xs:documentation>Indicates that the command is available to be invoked from within the thermostat shell.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="cli">
        <xs:annotation>
          <xs:documentation>Indicates that the command is available to be invoked as an argument to the main thermostat program.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="bundles">
  <xs:annotation>
    <xs:documentation>
      Specifies OSGi bundles
    </xs:documentation>
  </xs:annotation>
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="bundle" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="bundle">
  <xs:annotation>
    <xs:documentation>
      Specifies an OSGi bundle
    </xs:documentation>
  </xs:annotation>
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="symbolic-name">
        <xs:annotation>
          <xs:documentation>
            The 'Bundle-SymbolicName' of the OSGi bundle
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element ref="version">
        <xs:annotation>
          <xs:documentation>
            The 'Bundle-Version' of the OSGi bundle
          </xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="configurations">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="configuration" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== zzambers/thermostat-ng_agent/vm-byteman/distribution/thermostat-plugin.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--

 Copyright 2012-2016 Red Hat, Inc.

 This file is part of Thermostat.

 Thermostat is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published
 by the Free Software Foundation; either version 2, or (at your
 option) any later version.

 Thermostat is distributed in the hope that it will be useful, but
 WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Thermostat; see the file COPYING.  If not see
 <http://www.gnu.org/licenses/>.

 Linking this code with other modules is making a combined work
 based on this code.  Thus, the terms and conditions of the GNU
 General Public License cover the whole combination.

 As a special exception, the copyright holders of this code give
 you permission to link this code with independent modules to
 produce an executable, regardless of the license terms of these
 independent modules, and to copy and distribute the resulting
 executable under terms of your choice, provided that you also
 meet, for each linked independent module, the terms and conditions
 of the license of that module.  An independent module is a module
 which is not derived from or based on this code.  If you modify
 this code, you may extend this exception to your version of the
 library, but you are not obligated to do so.  If you do not wish
 to do so, delete this exception statement from your version.

-->
<plugin xmlns="http://icedtea.classpath.org/thermostat/plugins/v1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://icedtea.classpath.org/thermostat/plugins/v1.0 http://icedtea.classpath.org/thermostat/docs/1.0/thermostat-plugin.xsd">
    <extensions>
        <extension>
            <name>agent</name>
            <bundles>
                <bundle><symbolic-name>com.redhat.thermostat.agent.ipc.common</symbolic-name><version>${project.version}</version></bundle>
                <bundle><symbolic-name>com.redhat.thermostat.agent.ipc.server</symbolic-name><version>${project.version}</version></bundle>
                <bundle><symbolic-name>com.redhat.thermostat.agent.ipc.unixsocket.server</symbolic-name><version>${project.version}</version></bundle>
                <bundle><symbolic-name>com.redhat.thermostat.agent.ipc.unixsocket.common</symbolic-name><version>${project.version}</version></bundle>
                <bundle><symbolic-name>com.redhat.thermostat.vm.byteman.common</symbolic-name><version>${project.version}</version></bundle>
                <bundle><symbolic-name>com.redhat.thermostat.vm.byteman.agent</symbolic-name><version>${project.version}</version></bundle>
                <bundle><symbolic-name>org.jboss.byteman.agent.install</symbolic-name><version>${byteman.osgi-version}</version></bundle>
                <bundle><symbolic-name>org.jboss.byteman.agent.submit</symbolic-name><version>${byteman.osgi-version}</version></bundle>
                <bundle><symbolic-name>jnr.unixsocket</symbolic-name><version>${jnr-unixsocket.version}</version></bundle>
                <bundle><symbolic-name>jnr.enxio</symbolic-name><version>${jnr-enxio.version}</version></bundle>
                <bundle><symbolic-name>jnr.constants</symbolic-name><version>${jnr-constants.version}</version></bundle>
                <bundle><symbolic-name>jnr.posix</symbolic-name><version>${jnr-posix.version}</version></bundle>
                <bundle><symbolic-name>jnr.ffi</symbolic-name><version>${jnr-ffi.version}</version></bundle>
                <bundle><symbolic-name>jnr.x86asm</symbolic-name><version>${jnr-x86asm.version}</version></bundle>
                <bundle><symbolic-name>jffi</symbolic-name><version>${jffi.version}</version></bundle>
                <bundle><symbolic-name>org.objectweb.asm</symbolic-name><version>${asm.version}</version></bundle>
            </bundles>
        </extension>
    </extensions>
</plugin>
